import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../../services/auth_service.dart';
import '../../services/product_service.dart';
import '../../services/user_service.dart';
// import '../../services/category_service.dart';
import '../../services/inventory_service.dart';
import '../../services/notification_service.dart';
import '../../services/order_service.dart';
import '../../services/report_service.dart';
// import '../../services/dashboard_service.dart';

final authServiceProvider = Provider((ref) => AuthService());
final productServiceProvider = Provider((ref) => ProductService());
final userServiceProvider = Provider((ref) => UserService());
// final categoryServiceProvider = Provider((ref) => CategoryService());
final inventoryServiceProvider = Provider((ref) => InventoryService());
final notificationServiceProvider = Provider((ref) => NotificationService());
final orderServiceProvider = Provider((ref) => OrderService());
final reportServiceProvider = Provider((ref) => ReportService());
// final dashboardServiceProvider = Provider((ref) => DashboardService());
